#ifndef WASM_DECOMP_ORIGINAL_H_GENERATED_
#define WASM_DECOMP_ORIGINAL_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'a' 'a' */
extern u32 (*Z_aZ_aZ_iiii)(u32, u32, u32);
/* import: 'a' 'b' */
extern void (*Z_aZ_bZ_vv)(void);
/* import: 'a' 'c' */
extern f32 (*Z_aZ_cZ_ff)(f32);
/* import: 'a' 'd' */
extern f64 (*Z_aZ_dZ_diii)(u32, u32, u32);
/* import: 'a' 'e' */
extern f32 (*Z_aZ_eZ_fv)(void);
/* import: 'a' 'f' */
extern u32 (*Z_aZ_fZ_ii)(u32);
/* import: 'a' 'g' */
extern f64 (*Z_aZ_gZ_dv)(void);
/* import: 'a' 'h' */
extern u32 (*Z_aZ_hZ_iiiii)(u32, u32, u32, u32);
/* import: 'a' 'i' */
extern void (*Z_aZ_iZ_viiii)(u32, u32, u32, u32);
/* import: 'a' 'j' */
extern void (*Z_aZ_jZ_vv)(void);
/* import: 'a' 'k' */
extern u32 (*Z_aZ_kZ_iii)(u32, u32);
/* import: 'a' 'l' */
extern u32 (*Z_aZ_lZ_iii)(u32, u32);
/* import: 'a' 'm' */
extern void (*Z_aZ_mZ_vi)(u32);
/* import: 'a' 'n' */
extern u32 (*Z_aZ_nZ_iiii)(u32, u32, u32);
/* import: 'a' 'o' */
extern u32 (*Z_aZ_oZ_iiiiii)(u32, u32, u32, u32, u32);
/* import: 'a' 'p' */
extern u32 (*Z_aZ_pZ_iii)(u32, u32);
/* import: 'a' 'q' */
extern u32 (*Z_aZ_qZ_iii)(u32, u32);
/* import: 'a' 'r' */
extern void (*Z_aZ_rZ_viii)(u32, u32, u32);
/* import: 'a' 'memory' */
extern wasm_rt_memory_t (*Z_aZ_memory);
/* import: 'a' 'table' */
extern wasm_rt_table_t (*Z_aZ_table);

/* export: 's' */
extern void (*WASM_RT_ADD_PREFIX(Z_sZ_vv))(void);
/* export: 't' */
extern void (*WASM_RT_ADD_PREFIX(Z_tZ_vi))(u32);
/* export: 'u' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_uZ_iv))(void);
/* export: 'v' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_vZ_iii))(u32, u32);
/* export: 'w' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_wZ_ii))(u32);
/* export: 'x' */
extern void (*WASM_RT_ADD_PREFIX(Z_xZ_vi))(u32);
/* export: 'y' */
extern void (*WASM_RT_ADD_PREFIX(Z_yZ_vi))(u32);
/* export: 'z' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_zZ_iii))(u32, u32);
/* export: 'A' */
extern void (*WASM_RT_ADD_PREFIX(Z_AZ_vv))(void);
/* export: 'B' */
extern void (*WASM_RT_ADD_PREFIX(Z_BZ_vi))(u32);
/* export: 'C' */
extern void (*WASM_RT_ADD_PREFIX(Z_CZ_vv))(void);
/* export: 'D' */
extern void (*WASM_RT_ADD_PREFIX(Z_DZ_vv))(void);
/* export: 'E' */
extern void (*WASM_RT_ADD_PREFIX(Z_EZ_vii))(u32, u32);
/* export: 'F' */
extern void (*WASM_RT_ADD_PREFIX(Z_FZ_vi))(u32);
/* export: 'G' */
extern void (*WASM_RT_ADD_PREFIX(Z_GZ_vi))(u32);
/* export: 'H' */
extern void (*WASM_RT_ADD_PREFIX(Z_HZ_vv))(void);
/* export: 'I' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_IZ_iv))(void);
/* export: 'J' */
extern void (*WASM_RT_ADD_PREFIX(Z_JZ_vv))(void);
/* export: 'K' */
extern void (*WASM_RT_ADD_PREFIX(Z_KZ_vi))(u32);
/* export: 'L' */
extern void (*WASM_RT_ADD_PREFIX(Z_LZ_vv))(void);
/* export: 'M' */
extern void (*WASM_RT_ADD_PREFIX(Z_MZ_vv))(void);
/* export: 'N' */
extern void (*WASM_RT_ADD_PREFIX(Z_NZ_vi))(u32);
/* export: 'O' */
extern void (*WASM_RT_ADD_PREFIX(Z_OZ_viiii))(u32, u32, u32, u32);
/* export: 'P' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_PZ_iv))(void);
/* export: 'Q' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_QZ_ii))(u32);
/* export: 'R' */
extern void (*WASM_RT_ADD_PREFIX(Z_RZ_vii))(u32, u32);
/* export: 'S' */
extern void (*WASM_RT_ADD_PREFIX(Z_SZ_vi))(u32);
#ifdef __cplusplus
}
#endif

#endif  /* WASM_DECOMP_ORIGINAL_H_GENERATED_ */
